### ISSUE TITLE
Sprachanpassungen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/be_password#10]
Verwendung von Language-Files und Platzhaltern für Sprachersetzungen.
~~Alex ist schon dran…~~

**Comment by alexplusde** [comment]
Memo an mich: Branch nochmal frisch vom Master ziehen.

**Comment by schuer** [comment]
Danach dann gerne eine 1.0 veröffentlichen, was? (@IngoWinter) Aktuell finde ich das AddOn nicht für die Allgemeinheit nutzbar, weil die Mail, die man bekommt, sehr äh… eigenwillig ausschaut ;)

<img width="556" alt="screenshot 2017-10-16 14 19 34" src="https://user-images.githubusercontent.com/1297466/31611614-1562c414-b27d-11e7-82c3-4e9c42523977.png">

**Comment by schuer** [comment]
Aber es funktioniert technisch sehr gut. Nicht, dass das falsch rüber kommt. Sehr cooles und wichtiges AddOn!

**Comment by IngoWinter** [comment]
@schuer kann es sein, dass du dir den "lang" Branch gezogen hast oder eine veraltete Version des "master" Branches? Deine Ansicht kann eigentlich nur daher kommen - das ist ein Commit von @alexplusde, der aber im master Branch nicht (mehr) drin ist https://github.com/FriendsOfREDAXO/be_password/commit/dd8fc95bd779a47e419879dc6431a2521994f7a7

**Comment by schuer** [comment]
@IngoWinter Ich hatte Alex’ zwei Commits im Master-Branch zurückgesetzt, weil sie dafür gesorgt haben, dass aufgrund der fehlenden Lang-Files eine Exception flog. Sie sind auch Bestandteil des Lang-Branches, deshalb werden sie irgendwann wieder zurück in Master gemerged werden, wenn Alex fertig ist mit den Anpassungen.

Jedenfalls: Der Screen zeigt den aktuellen Zustand des Master-Branches, so wie er von akuenis rübergekommen ist. Funktioniert, taugt nur nicht für die allgemeine Nutzerschaft, so ganz ohne die Sprachersetzungen.

**Comment by IngoWinter** [comment]
@schuer der master Branch sieht aktuell so aus: https://github.com/FriendsOfREDAXO/be_password/blob/master/install.php

**Comment by schuer** [comment]
Ingo hat recht, wir haben es eben im Slack geklärt: Ich hatte erst eine alte Version aus dem Installer installiert, später dann den Stand aus dem Git drübergebügelt. Leider wird damit die Config nicht geupdatet, so dass bei mir die Version ohne Sprachersetzung weiterhin aktiv war.
