### ISSUE TITLE
Nicht erkennbar machen, dass das Konto existiert

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/be_password#14]
d.h. immer die gleiche Meldung rausschicken wäre z.B. ein Weg,

Jeder bekommt immer die Meldung. "Passwortlink ging raus".

**Comment by alexplusde** [comment]
Das ist so ein DSGVO-Ding, oder? Die Seite darf nicht verraten, dass es die E-Mail-Adresse gibt?
