### ISSUE TITLE
Kompatibilität mit neuer REX-Loginseite herstellen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/be_password#19]
Reminder: Sofern redaxo/redaxo#3887 gemerged wird, müsste das AddOn nachziehen, damit die UI einheitlich ist.

**Comment by schuer** [comment]
Inzwischen gemerged worden. Be_password muss nun dahingehend angepasst werden, sich in die neue Login-Page zu integrieren. Aktuell tauscht das AddOn die gesamte Login-Box aus und verwirft dabei auch zwangsläufig das Hintergrund-Element. Hier müsste zukünftig ein bisschen differenziert werden, so dass statt der gesamten Box nur noch dessen Body und Footer von be_password ausgetauscht werden.

Passiert alles im JS und ist kein allzu großer Aufriss. Kann ich mich bei Gelegenheit drum kümmern, falls niemand anderes möchte.

**Comment by IngoWinter** [comment]
Gute Sache das 👍
