### ISSUE TITLE
Absenderemailadresse aus PHP-Mailer-Settings nutzen

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/be_password#2]
Hey, ich habe das Addon gerade verwendet, dachte aber erst es würde nicht funktionieren, weil das Mail nicht ankam. Tatsächlich landete es aber im Spam weil die Absenderemailadresse der Serverhostname etc. ist statt die angegebene Adresse im PHPMailer. Das sollte unbedingt angepasst werden.

**Comment by akuehnis** [comment]
Ich kann das nicht reproduzieren, bei mir passiert genau das. BE-Passwort erstellt nur eine Instanz von rex_mailer und passt  Subject, Body und Empfänger an. Alles andere wird von rex_mailer übernommen.

**Comment by schuer** [comment]
Ich habe es gerade nochmal geprüft, und es funktionierte wie geplant. Kann auch im Code nichts finden, was die Absenderadresse durcheinander bringen könnte.

Ich schließe mal, @phoebusryan, und solltest du weiterhin den Fehler haben, mach’s gerne nochmal auf.

**Comment by phoebusryan** [comment]
Alles klar, danke Dirk. Möglicherweise lags an meinem Code damals :)
