### ISSUE TITLE
Konfiguration im Backend mehrsprachig aufziehen oder entfernen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/be_password#20]
Die Konfiguration im Backend ist aktuell nur auf deutsch verfügbar. Hier sollten wir entweder eine Mehrsprachigkeit einbringen, oder aber — my 2 cents —, die Konfigurationsseite komplett entfernen. Es ist der Mail-Betreff und der Mail-Inhalt konfigurierbar, braucht man so ein Feature wirklich?

<img width="1175" alt="Screenshot 2020-10-09 at 12 00 55" src="https://user-images.githubusercontent.com/1297466/95570590-6c2fb400-0a27-11eb-93d8-3e05750b838c.png">

**Comment by IngoWinter** [comment]
Von mir aus machs weg. Ich glaube ich habe da noch nie draufgeklickt :)

**Comment by alxndr-w** [comment]
Schön und gut - wo kann der Text jetzt eingestellt werden?

**Comment by schuer** [comment]
Gar nicht mehr. Dafür hätten wir die Konfigurationsseite mehrsprachig aufziehen müssen. Um es einfacher zu halten, haben wir uns dagegen entschieden.

**Comment by alxndr-w** [comment]
Woher stammt dann der Text der E-Mail?

**Comment by schuer** [comment]
Er befindet sich nun in den Language-Files, etwa hier: https://github.com/FriendsOfREDAXO/be_password/blob/3c63fb7e370fa2a9376c9897f291797a8604e1ed/lang/de_de.lang#L14

**Comment by alxndr-w** [comment]
Alles klar, damit kann's ja dann doch bearbeitet werden mit einer eigenen lang-Datei im Project-Addon, oder nicht? Gehört imho in die README
