### ISSUE TITLE
Es wird keine E-Mail verschickt

### ISSUE THREAD

**Issue by rotzek** [FriendsOfREDAXO/be_password#26]
Ich habe das Addon unter verschiedenen Redaxo-Installationen im Einsatz und bei keiner wird eine Email verschickt.
Läuft das Addon mit aktuellem Redaxo 5.13 und aktuellem PhpMailer 2.11.1? 
Muss ich irgendetwas beachten?

**Comment by alxndr-w** [comment]
Wird die Testmail von PHPMailer verschickt? Ist eine Mail-Adresse am Benutzer hinterlegt?

**Comment by rotzek** [comment]
Peinlich... Daran hat es wohl gelegen... Danke Alex!

**Comment by alxndr-w** [comment]
Passiert :)
