### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/be_password#28]
**Description / Beschreibung**

![image](https://user-images.githubusercontent.com/330516/184218806-677990a3-b41c-4982-9e56-5421fad21f1d.png)

**Affected versions / Verwendete Versionen**

<details>
<summary>System report (REDAXO 5.14.1, PHP 8.0.8, MySQL 5.7.34)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.14.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.0.8      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.34 |
| Character set | utf8mb4      |

| Server        |               |
| ------------: | :------------ |
|            OS | Darwin        |
|          SAPI | cgi-fcgi      |
|     Webserver | Apache/2.4.48 |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/15.6 |
|      Protocol | HTTP/1.1    |
|         HTTPS | yes         |

| Packages                  |            |
| ------------------------: | :--------- |
|              accessdenied | 2.0.1      |
|                   adminer | 1.9.2      |
|                    backup | 2.8.2      |
|               be_password | 2.0.0      |
|                  be_style | 3.1.0      |
|       be_style/customizer | 3.1.0      |
|           be_style/redaxo | 3.1.0      |
|                   bloecks | 3.1.1      |
|          bloecks/cutncopy | 3.1.1      |
|           consent_manager | 3.0.7      |
|                   cronjob | 2.9.0      |
|                     debug | 1.2.2      |
|                 developer | 3.9.0      |
|                focuspoint | 4.0.2      |
|                 gridblock | 1.1.6      |
| gridblock/contentsettings | 1.6.2      |
|    gridblock/synchronizer | 1.0        |
|               insert_text | 2.0.1      |
|                   install | 2.10.0     |
|                  markitup | 3.7.1      |
|                    mblock | 3.4.4      |
|             media_manager | 2.13.0     |
|              media_srcset | 2.1.0      |
|                 mediapool | 2.12.0     |
|                  metainfo | 2.9.0      |
|                     mform | 7.0.1      |
|                mform/docs | 1.1        |
|             modulsammlung | 4.15.2     |
|                 phpmailer | 2.11.2     |
|                   project | dev        |
|                  redactor | 2.3.0      |
|                     sprog | 1.3.0      |
|                 structure | 2.14.1     |
|         structure/content | 2.14.1     |
|                     theme | 1.3.3      |
|                  ui_tools | 1.2.1      |
|        ui_tools/selectize | 0.2.0      |
|                  uploader | 2.3.0      |
|                       url | 2.0.1      |
|                     users | 2.9.0      |
|                 warehouse | 0.3.1      |
|                      ycom | 4.0.7      |
|                 ycom/auth | 4.0.7      |
|                ycom/group | 4.0.7      |
|                     yform | 4.0.2      |
|               yform/email | 4.0.2      |
|             yform/manager | 4.0.2      |
|                yform/rest | 4.0.2      |
|               yform/tools | 4.0.2      |
|                  yform_ui | 1.0.1      |
|           yform_usability | 2.0.5      |
|               ynewsletter | 1.5.1      |
|                  yrewrite | 2.9.0      |

</details>

**Did it whoops? / Whoops erhalten?**

Die Warnings erscheinen auf der Seite auf der ich die E-Mail Adresse eingeben kann.

**Comment by IngoWinter** [comment]
Ist bereits gefixt (siehe die letzten Commits), allerdings noch nicht im Installer.

**Comment by alxndr-w** [comment]
Ich habe die dev-Version in den Installer gepackt. Bitte testen und releasen.
