### ISSUE TITLE
Addon zu FOR transferieren?

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/be_password#4]
Moin

Magst du das Addon zu [FriendsOfREDAXO](https://github.com/orgs/FriendsOfREDAXO/dashboard) transferieren? Dann würde es sicherlich häufiger genutzt und gepflegt werden - ich habs gerade auch nur durch Zufall über den Slack Channel gefunden :)

LG Ingo

**Comment by akuehnis** [comment]
Fehler beim Transfer: You don’t have the permission to create repositories on FriendsOfREDAXO

**Comment by IngoWinter** [comment]
Anscheinend dürfen nicht FOR Mitglieder kein Repository an FOR übertragen. Sorry, das wusste ich bisher selbst nicht :)
Du solltest eine Einladung zu FOR bekommen. Falls dir das zuviel Wiggel ist, kannst du mir auch einfach das Repo übertragen, dann übertrage ichs weiter zu FOR. Oder du packst ne MIT Lizenz dran und ich forke das einfach bei FOR. Auf jeden Fall schon mal danke!

**Comment by schuer** [comment]
Scheint geklappt zu haben. Saucool, @akuehnis! Und willkommen bei FOR :)

**Comment by schuer** [comment]
Wer macht denn den Lead, @akuehnis oder @IngoWinter?
Und wir müssten das Repo noch auf `be_password` umbenennen…

**Comment by IngoWinter** [comment]
Umbenennen mach du mal. Lead kann ich machen, wenn @akuehnis das möchte. Allerdings habe ich bisher ausser nem PR zur Optik noch nix hier gemacht ^^

**Comment by akuehnis** [comment]
Sehr, sehr gerne, ich bin gerade nicht in der Lage aktiv auf Request einzugehen.

**Comment by IngoWinter** [comment]
https://youtu.be/mdIP3hyxi3k
