### ISSUE TITLE
Screenshots für README

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/be_password#6]
Kann ich gerne übernehmen, sobald etwas Zeit ist, und assigne das Issue deshalb an mich.
Falls es aber jemand vorher machen möchte, nur zu!

**Comment by schuer** [comment]
Es sollten allerdings noch irgendwelche Texte angepasst werden, oder wie war das @IngoWinter? Das sollte ich dann vielleicht abwarten vorm Screenshot.

**Comment by IngoWinter** [comment]
@alexplusde kann das ja eben flink direkt reineditieren und dann Bescheid geben. Auf Dauer muss noch Mehrsprachigkeit über i18n rein, aber da habe ich gerade keine Muße für :)

**Comment by IngoWinter** [comment]
@alexplusde die Texte liegen in der js Datei in /assets und in den 3 php dateien in /views

**Comment by alexplusde** [comment]
in der js-Datei? Wirklich? Hab nur in pages und views was gefunden

**Comment by IngoWinter** [comment]
@alexplusde nee sorry natürlich nicht in der js-Datei :)

**Comment by alexplusde** [comment]
klar, hab' ja ne Branch angelegt und mach nen regulären PR

**Comment by schuer** [comment]
Ich habe die Screenshots schonmal gemacht. Die Textanpassungen war dafür nicht notwendig, die Screens zeigen nur Formulare.
