### ISSUE TITLE
HTML/CSS noch besser an REX anpassen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/be_password#7]
Ich wollte gestern Screenshots machen, dabei ist mir aufgefallen, dass sich das Eingabefeld für die E-Mailadresse noch nicht 100% REDAXO-nativ anfühlt. REX benutzt eine zusätzliche `<div class="input-group">` mit Icon. Vielleicht wollen wir das noch be_password anpassen. Außerdem sollte der Abbrechen-Button vermutlich rechts ausgerichtet stehen.

**Comment by IngoWinter** [comment]
Tob dich aus - mir ist das Hupe :)
