### ISSUE TITLE
Passwortregeln beachten (REX 5.4)

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/be_password#9]
Das neue Passwort wird aktuell in jeglicher Form — auch wenn es nur ein Zeichen ist — akzeptiert. Das sollte wohl eher nicht so sein. Zudem kamen mit REX 5.4 die [Passwortregeln](https://github.com/redaxo/redaxo/issues/1331) ins Spiel, die wir sicherlich beachten sollten.

Mit den letzten Updates ist mir allerdings aufgefallen, dass dafür auch das Formular (»Neues Passwort festlegen«) angepasst werden müsste: Aktuell kommt das Inputfeld nur, wenn keine Fehler und kein Erfolg gemeldet wird. Mit den Passwortregeln müssten wir das genauer handhaben und das Inputfeld auch bei bestimmten Fehlern zeigen.

**Comment by schuer** [comment]
Das mit den Password-Policies ist leider gar nicht so einfach. Ich wollte es gerade umsetzen, und serverseitig ist das auch fix gemacht, allerdings spielt der Client mit rein: Das Passwort wird vermutlich aus Sicherheitsgründen — wir befinden uns ja außerhalb des REDAXO-Backends — als [sha1](https://github.com/FriendsOfREDAXO/be_password/blob/master/assets/javascript/be_password.js#L46) übertragen, so dass es serverseitig bereits verschlüsselt ankommt und nicht mehr auf Passwortregeln geprüft werden kann.

Ich denke, wir sollten das nicht ändern, allerdings haben wir dann vermutlich keine Chance mehr, die Passwortregeln zu beachten. Außer — und das wäre mein Vorschlag — wir notieren innerhalb von be_password, wenn ein Passwort zurückgesetzt wurde, und forcieren danach innerhalb des REDAXO-Backends eine erneute Änderung des Passworts. Das könnte man z. B. dadurch realisieren, dass immer auf die Profilseite redirected wird und der Nutzer nichts im Backend tun kann, solange nicht das Passwort neu gesetzt wurde.

Was haltet ihr von der Idee? Oder habt ihr vielleicht eine bessere?

**Comment by gupi** [comment]
Aber ist das Ändern im Profil nicht genau so ein client Vorgang mit verschlüsseltem Passwort? Ich sehe keinen Unterschied zwischen dem Passwort-  und dem Profil-Formular. Entweder bereits im Client während der Eingabe per js prüfen, oder prüfen entfällt wenn verschlüsselt zum Server übertragen wird.

**Comment by schuer** [comment]
@gupi Auf der Profilseite wird noch das rohe Passwort geprüft, bevor es verschlüsselt in die Datenbank kommt. In be_password passiert alles jedoch als nicht-eingeloggter Benutzer, deshalb wird das Passwort aus Sicherheitsgründen schon clientseitig gehasht, bevor es übertragen wird. Nun könnte man zwar JS-seitig die Passwortregeln prüfen, das wäre allerdings mit ziemlichem Aufwand verbunden, während die serverseitige Prüfung bereits vollständig implementiert wurde.

**Comment by gharlan** [comment]
Das Problem mit dem clientseitigen Hashen hatten wir im Core auch, denn im Profil und in der Userverwaltung war das bis 5.3 auch drin.
Eine Diskussion dazu fand hier statt: https://github.com/redaxo/redaxo/issues/1361
Woraufhin wir das clientseitige Hashen (der Mehrwert ist sowieso sehr begrenzt aus meiner Sicht, siehe Issue dort) an den entsprechenden Stellen entfernt haben.
Beim Login haben wir es drin gelassen, da es dort nicht "störte" und das ja die häufigste Aktion ist, wo das Passwort übertragen wird.

Ich fände es ok, das clientseitige Hashen hier im Addon auch wegzulassen.

**Comment by schuer** [comment]
Danke für euer Feedback! Ohne clientseitiges Hashen war es eine Kleinigkeit, die Passwortregeln zu implementieren. Schaut gerne mal, ob ich alles richtig gemacht habe.
